name: GCC-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install avr-gcc, avrdude
      run: |
        sudo apt-get update
        sudo apt-get install gcc-avr binutils-avr avr-libc
        sudo apt-get install avrdude

    - name: make
      run: make